[
  {
    price: 499000,
    unit: 'xuất',
    image: 'https://toplist.vn/images/800px/buffet-valentino-99k-570588.jpg',
    name: 'Mâm hải sản BBQ',
    catalog: 'Các món mới',
    slug: 'mam-hai-san-bbq',
  },
  {
    price: 499000,
    unit: 'xuất',
    image: 'https://static.riviu.co/960/image/2021/01/04/6496fec95fc3a842363ffd30eb96e01e_output.jpeg',
    name: 'Mâm lẩu hải sản khổng lồ',
    catalog: 'Các món mới',
    slug: 'mam-lau-hai-san-khong-lo',
  },
  {
    price: 199000,
    unit: 'dĩa',
    name: 'Mực Ống Đông Tàu Sốt S1',
    image:
      'https://brand-pcms.ggg.systems/media/catalog/product/cache/fccf9bc1c56510f6f2e84ded9c30a375/m/u/muc_ong_dong_tau_sot_s1.jpg',
    catalog: 'Món đặc biệt',
    slug: 'muc-ong-dong-tau-sot-s1',
  },
  {
    price: 199000,
    unit: 'dĩa',
    name: 'Mực Nang Tàu Bay Sốt S1',
    image:
      'https://brand-pcms.ggg.systems/media/catalog/product/cache/fccf9bc1c56510f6f2e84ded9c30a375/m/u/muc_nang_tau_bay_sot_s1.jpg',
    catalog: 'Món đặc biệt',
    slug: 'muc-nang-tau-bay-sot-s1',
  },
  {
    price: 99000,
    unit: 'con',
    name: 'Bào Ngư Sốt Bơ Tỏi',
    image:
      'https://brand-pcms.ggg.systems/media/catalog/product/cache/fccf9bc1c56510f6f2e84ded9c30a375/1/5/15545_Bao_Ngu_Sot_Bo_Toi_1_Con_3.png',
    catalog: 'Món đặc biệt',
    slug: 'bao-ngu-sot-bo-toi',
  },
  {
    price: 199000,
    unit: 'kg',
    name: 'Bạch Tuộc Đại Dương Sốt Hải Sản',
    image:
      'https://brand-pcms.ggg.systems/media/catalog/product/cache/fccf9bc1c56510f6f2e84ded9c30a375/3/2/32_Bach_Tuoc_Dai_Duong_Sot_Hai_San_1_1.jpg',
    catalog: 'Món đặc biệt',
    slug: 'bach-tuoc-dai-duong-sot-hai-san',
  },
  {
    price: 119000,
    unit: 'dĩa',
    name: 'Sò Điệp Nhật',
    image:
      'https://brand-pcms.ggg.systems/media/catalog/product/cache/fccf9bc1c56510f6f2e84ded9c30a375/2/7/27_So_Diep_Nhat_1_1.jpg',
    catalog: 'Món đặc biệt',
    slug: 'so-diep-nhat',
  },
  {
    price: 199000,
    unit: 'dĩa',
    name: 'Tôm Song Tấu',
    image:
      'https://brand-pcms.ggg.systems/media/catalog/product/cache/fccf9bc1c56510f6f2e84ded9c30a375/5/9/5929_Tom_Song_Tau_1_1.jpg',
    catalog: 'Món đặc biệt',
    slug: 'tom-song-tau',
  },
  {
    price: 119000,
    unit: 'dĩa',
    name: 'Mực Ống Giấy Bạc Sốt Hải Sản',
    image:
      'https://brand-pcms.ggg.systems/media/catalog/product/cache/fccf9bc1c56510f6f2e84ded9c30a375/7/3/73_Muc_Ong_Giay_Bac_Sot_Hai_San_1_1.jpg',
    catalog: 'Món đặc biệt',
    slug: 'muc-ong-giay-bac-sot-hai-san',
  },
  {
    price: 189000,
    unit: 'kg',
    name: 'Cá Hồi Giấy Bạc',
    image:
      'https://brand-pcms.ggg.systems/media/catalog/product/cache/fccf9bc1c56510f6f2e84ded9c30a375/8/5/850_Ca_Hoi_Giay_Bac_1_1.jpg',
    catalog: 'Món đặc biệt',
    slug: 'ca-hoi-giay-bac',
  },
  {
    price: 125000,
    unit: 'dĩa',
    name: 'Chả giò tôm cua',
    image: 'https://www.tubepxuyenviet.net/upload/images/dam-da-voi-cha-gio-tom-cua.jpg',
    catalog: 'Các món Khai Vị',
    slug: 'cha-gio-tom-cua',
  },
  {
    price: 65000,
    unit: 'dĩa',
    name: 'Khoai tây chiên',
    image: 'https://ruavangfood.com/storage/uploads/2021/11/13/618f1008a2f85.png',
    catalog: 'Các món Khai Vị',
    slug: 'khoai-tay-chien',
  },
  {
    price: 45000,
    unit: 'dĩa',
    name: 'Đậu hũ giòn',
    image: 'https://cdn.tgdd.vn/2021/05/CookProduct/thumbcmscn-1200x676-3.jpg',
    catalog: 'Các món Khai Vị',
    slug: 'dau-hu-gion',
  },
  {
    price: 125000,
    unit: 'dĩa',
    name: 'Râu mực chiên giòn',
    image: 'https://chamucnhatrang.com/wp-content/uploads/2015/03/rau-muc-tam-bot-chien.jpg',
    catalog: 'Các món Khai Vị',
    slug: 'rau-muc-chien-gion',
  },
  {
    price: 145000,
    unit: 'dĩa',
    name: 'Cá trứng lăn bột',
    image: 'https://thitngonnhapkhau.vn/wp-content/uploads/2022/12/ca20trung20gia20re20o20sg.jpg',
    catalog: 'Các món Khai Vị',
    slug: 'ca-trung-lan-bot',
  },
  {
    price: 125000,
    unit: 'dĩa',
    name: 'Gỏi hải sản',
    image: 'https://haisantrungnam.vn/wp-content/uploads/2020/11/cach-lam-goi-hai-san-1.jpg',
    catalog: 'Các món gỏi',
    slug: 'goi-hai-san',
  },
  {
    price: 125000,
    unit: 'dĩa',
    name: 'Gỏi mực thái lan',
    image: 'https://cdn.cet.edu.vn/wp-content/uploads/2019/10/goi-muc-thai-lan-gion-ngon.jpg',
    catalog: 'Các món gỏi',
    slug: 'goi-muc-thai-lan',
  },
  {
    price: 85000,
    unit: 'dĩa',
    name: 'Gỏi khô cá sặc',
    image: 'https://cdn.tgdd.vn/2021/02/CookProduct/1200676nhasd-1200x675.jpg',
    catalog: 'Các món gỏi',
    slug: 'goi-kho-ca-sac',
  },
  {
    price: 125000,
    unit: 'dĩa',
    name: 'Gỏi tôm sống',
    image: 'https://haisangiobien.com/wp-content/uploads/2021/11/goi-tom-song.jpg',
    catalog: 'Các món gỏi',
    slug: 'goi-tom-song',
  },
  {
    price: 39000,
    unit: 'chén',
    name: 'Súp cua',
    image: 'https://nghebep.com/wp-content/uploads/2017/09/sup-cua-cho-be.jpg',
    catalog: 'Các món súp',
    slug: 'sup-cua',
  },
  {
    price: 39000,
    unit: 'chén',
    name: 'Súp tôm',
    image: 'https://cdn.daynauan.info.vn/wp-content/uploads/2020/08/sup-tom.jpg',
    catalog: 'Các món súp',
    slug: 'sup-tom',
  },
  {
    price: 49000,
    unit: 'chén',
    name: 'Súp hải sản rong biển',
    image: 'https://thegioihaisan.vn/wp-content/uploads/2016/06/1380070452-canh-tom-2-.jpg',
    catalog: 'Các món súp',
    slug: 'sup-hai-san-rong-bien',
  },
  {
    price: 110000,
    unit: 'tô',
    name: 'Cháo hải sản',
    image: 'https://www.hoidaubepaau.com/wp-content/uploads/2019/06/cach-nau-chao-hai-san.jpg',
    catalog: 'Các món cháo',
    slug: 'chao-hai-san',
  },
  {
    price: 120000,
    unit: 'tô',
    name: 'Cháo tôm hùm',
    image: 'https://cdn.huongnghiepaau.com/wp-content/uploads/2020/10/chao-tom-hum.jpg',
    catalog: 'Các món cháo',
    slug: 'chao-tom-hum',
  },
  {
    price: 110000,
    unit: 'tô',
    name: 'Cháo nghêu',
    image: 'https://wikiohana.net/wp-content/uploads/2019/11/cach-nau-chao-ngheu.jpg',
    catalog: 'Các món cháo',
    slug: 'chao-ngheu',
  },
  {
    price: 110000,
    unit: 'tô',
    name: 'Cháo hàu',
    image: 'https://haisankieuhung.com/wp-content/uploads/2019/11/chao-hau-voi-hanh.png',
    catalog: 'Các món cháo',
    slug: 'chao-hau',
  },
  {
    price: 110000,
    unit: 'dĩa',
    name: 'Cơm chiên hải sản',
    image: 'https://vn1.vdrive.vn/haisancuabien.com/2022/01/Hai-San-Cua-Bien-Thuc-Don-30-Mon-Man-Com-Rang-Hai-San.jpg',
    catalog: 'Cơm chiên',
    slug: 'com-chien-hai-san',
  },
  {
    price: 110000,
    unit: 'dĩa',
    name: 'Cơm chiên dương châu',
    image: 'https://ameovat.com/wp-content/uploads/2016/05/cach-lam-com-chien-duong-chau-600x481.jpg',
    catalog: 'Cơm chiên',
    slug: 'com-chien-duong-chau',
  },
  {
    price: 110000,
    unit: 'dĩa',
    name: 'Cơm chiên cá mặn',
    image: 'https://monngonmoingay.com/wp-content/uploads/2015/09/ComChienCaMan_540_360.jpg',
    catalog: 'Cơm chiên',
    slug: 'com-chien-ca-man',
  },
  {
    price: 110000,
    unit: 'dĩa',
    name: 'Cơm chiên cua',
    image:
      'http://cdn.tgdd.vn/Files/2020/07/02/1267044/bo-tui-ngay-cong-thuc-lam-com-chien-cua-chinh-goc-nguoi-hoa-cho-ca-gia-dinh-202007020937283816.jpg',
    catalog: 'Cơm chiên',
    slug: 'com-chien-cua',
  },
  {
    price: 110000,
    unit: 'dĩa',
    name: 'Mì xào hải sản',
    image: 'https://i.ytimg.com/vi/Z-2DBXPsg2M/maxresdefault.jpg',
    catalog: 'Mì-miến xào',
    slug: 'mi-xao-hai-san',
  },
  {
    price: 110000,
    unit: 'dĩa',
    name: 'Mì xào cua',
    image: 'https://cdn.daynauan.info.vn/wp-content/uploads/2015/06/mien-xao-cua.jpg',
    catalog: 'Mì-miến xào',
    slug: 'mi-xao-cua',
  },
  {
    price: 110000,
    unit: 'dĩa',
    name: 'Miến xào hải sản',
    image: 'https://cdn.netspace.edu.vn/images/2020/04/24/cach-lam-mien-xao-hai-san-1-800.jpg',
    catalog: 'Mì-miến xào',
    slug: 'mien-xao-hai-san',
  },
  {
    price: 110000,
    unit: 'dĩa',
    name: 'Miến xào cua',
    image: 'https://image-us.eva.vn/upload/3-2020/images/2020-07-27/image2-1595836344-541-width739height491.png',
    catalog: 'Mì-miến xào',
    slug: 'mien-xao-cua',
  },
  {
    price: 250000,
    unit: 'xuất',
    name: 'Lẩu nấm hải sản',
    image: 'https://biovegi.com.vn/wp-content/uploads/2018/12/lau-nam-hai-san.png',
    catalog: 'Các món lẩu',
    slug: 'lau-nam-hai-san',
  },
  {
    price: 280000,
    unit: 'xuất',
    name: 'Lẩu thái hải sản',
    image: 'https://nhahanghuongsen.com.vn/wp-content/uploads/2015/05/lau-hai-san-thai-lan.jpg',
    catalog: 'Các món lẩu',
    slug: 'lau-thai-hai-san',
  },
  {
    price: 250000,
    unit: 'xuất',
    name: 'Lẩu kim chi hải sản',
    image:
      'https://www.unileverfoodsolutions.com.vn/dam/global-ufs/mcos/phvn/vietnam/calcmenu/recipes/VN-recipes/fish-&-other-seafood-dishes/seafood-kim-chi-hotpot/main-header.jpg',
    catalog: 'Các món lẩu',
    slug: 'lau-kim-chi-hai-san',
  },
  {
    price: 250000,
    unit: 'xuất',
    name: 'Lẩu thái tôm',
    image: 'https://i.ytimg.com/vi/YKXBZ6eHkwQ/maxresdefault.jpg',
    catalog: 'Các món lẩu',
    slug: 'lau-thai-tom',
  },
  {
    price: 250000,
    unit: 'xuất',
    name: 'Lẩu cua',
    image: 'https://wikiohana.net/wp-content/uploads/2018/12/hoan-thanh-mon-lau-cua-bien.jpg',
    catalog: 'Các món lẩu',
    slug: 'lau-cua',
  },
  {
    price: 500000,
    unit: 'kg',
    name: 'Tôm sú rang me',
    image: 'https://cdn.daynauan.info.vn/wp-content/uploads/2019/01/tom-rang-me.jpg',
    catalog: 'Tôm sú',
    slug: 'tom-su-rang-me',
  },
  {
    price: 500000,
    unit: 'kg',
    name: 'Tôm sú rang muối',
    image: 'https://menu24h.vn/static/uploads/uploads/2015/07/tom-rang-muoi-nau-an-tai-nha.jpg',
    catalog: 'Tôm sú',
    slug: 'tom-su-rang-muoi',
  },
  {
    price: 500000,
    unit: 'kg',
    name: 'Tôm sú nướng muối ớt',
    image: 'https://canghaisan.com/wp-content/uploads/2020/11/74-1.jpg',
    catalog: 'Tôm sú',
    slug: 'tom-su-nuong-muoi-ot',
  },
  {
    price: 500000,
    unit: 'kg',
    name: 'Tôm sú nướng mọi',
    image: 'http://www.nhahangquangon.com/wp-content/uploads/2021/10/tom-su-nuong-moi2.jpg',
    catalog: 'Tôm sú',
    slug: 'tom-su-nuong-moi',
  },
  {
    price: 500000,
    unit: 'kg',
    name: 'Tôm sú nướng bơ tỏi',
    image:
      'https://cdn.tgdd.vn/Files/2021/01/02/1317375/cach-lam-tom-sot-bo-toi-thom-lung-ca-nha-ai-cung-me-202106191434100738.jpg',
    catalog: 'Tôm sú',
    slug: 'tom-su-nuong-bo-toi',
  },
  {
    price: 500000,
    unit: 'kg',
    name: 'Tôm sú hấp',
    image:
      'https://cdn.tgdd.vn/Files/2018/12/31/1141695/cung-lam-tom-su-hap-bia-thom-lung-cho-bua-tiec-ngay-xuan-202109221611247071.jpg',
    catalog: 'Tôm sú',
    slug: 'tom-su-hap',
  },
  {
    price: 400000,
    unit: 'dĩa',
    name: 'Tôm hùm tiết canh',
    image:
      'http://file.hstatic.net/1000030244/file/tiet-canh-tom-hum-1__1__99983a8c495d4a46b670b462c8adccd0_grande.jpg',
    catalog: 'Tôm hùm',
    slug: 'tom-hum-tiet-canh',
  },
  {
    price: 650000,
    unit: 'kg',
    name: 'Tôm hùm rang muối',
    image: 'https://file.hstatic.net/1000166699/file/46_ba5df0688ff44af7be482dba9d5d9070_grande.png',
    catalog: 'Tôm hùm',
    slug: 'tom-hum-rang-muoi',
  },
  {
    price: 650000,
    unit: 'kg',
    name: 'Tôm hùm rang me',
    image: 'http://file.hstatic.net/1000030244/file/tom-hum-sot-me-1_dde40554e01749c6ba24a286db0a820f_grande.jpg',
    catalog: 'Tôm hùm',
    slug: 'tom-hum-rang-me',
  },
  {
    price: 650000,
    unit: 'kg',
    name: 'Tôm hùm nướng mọi',
    image:
      'https://cdn.tgdd.vn/Files/2019/05/22/1168352/cach-lam-tom-hum-nuong-muoi-ot-an-mot-phat-la-ghien-202206171501141062.jpg',
    catalog: 'Tôm hùm',
    slug: 'tom-hum-nuong-moi',
  },
  {
    price: 650000,
    unit: 'kg',
    name: 'Tôm hùm nướng phô mai bơ tỏi',
    image: 'https://chefdzung.com.vn/uploads/images/bai-viet/71266393-2454353044844960-8538313994249699328-o.jpg',
    catalog: 'Tôm hùm',
    slug: 'tom-hum-nuong-pho-mai-bo-toi',
  },
  {
    price: 650000,
    unit: 'kg',
    name: 'Tôm hùm hấp',
    image:
      'http://cdn.tgdd.vn/Files/2020/02/28/1239091/cac-cach-hap-tom-hum-cuc-ky-ngon-ma-don-gian-tai-nha-202112310954112612.jpg',
    catalog: 'Tôm hùm',
    slug: 'tom-hum-hap',
  },
  {
    price: 200000,
    unit: 'kg',
    name: 'Mực lá nướng mối ớt',
    image: 'https://cdn.beptruong.edu.vn/wp-content/uploads/2018/05/muc-nuong-muoi-ot.jpg',
    catalog: 'Mực lá',
    slug: 'muc-la-nuong-moi-ot',
  },
  {
    price: 200000,
    unit: 'kg',
    name: 'Mực lá nướng sa tế',
    image: 'https://cdn.beptruong.edu.vn/wp-content/uploads/2018/05/muc-nuong-muoi-ot.jpg',
    catalog: 'Mực lá',
    slug: 'muc-la-nuong-sa-te',
  },
  {
    price: 200000,
    unit: 'kg',
    name: 'Mực lá nướng mọi',
    image: 'https://nhabobeerzone.com/uploads/source/hinh-anh/anh-do-an/hai-san-oc-ca/muc-bach-tuoc/muc-nuong-moi.jpg',
    catalog: 'Mực lá',
    slug: 'muc-la-nuong-moi',
  },
  {
    price: 200000,
    unit: 'kg',
    name: 'Mực lá chiên bột',
    image: 'https://bizweb.dktcdn.net/100/400/734/products/20201112105012-c10f93e7.png?v=1616746458127',
    catalog: 'Mực lá',
    slug: 'muc-la-chien-bot',
  },
  {
    price: 200000,
    unit: 'kg',
    name: 'Mực lá chiên nước mắm',
    image: 'https://bizweb.dktcdn.net/100/400/734/products/20201112105012-c10f93e7.png?v=1616746458127',
    catalog: 'Mực lá',
    slug: 'muc-la-chien-nuoc-mam',
  },
  {
    price: 200000,
    unit: 'kg',
    name: 'Mực lá chiên giòn',
    image: 'https://bizweb.dktcdn.net/100/400/734/products/20201112105012-c10f93e7.png?v=1616746458127',
    catalog: 'Mực lá',
    slug: 'muc-la-chien-gion',
  },
  {
    price: 200000,
    unit: 'kg',
    name: 'Mực ống chiên nước mắm',
    image: 'https://haisancoto.com/uploads/images/muc-ong-chien-nuoc-mam.jpg',
    catalog: 'Mực ống',
    slug: 'muc-ong-chien-nuoc-mam',
  },
  {
    price: 200000,
    unit: 'kg',
    name: 'Mực ống hấp hành gừng',
    image: 'https://vuahaisan.vn/wp-content/uploads/2022/06/muc-ong-hap.jpg',
    catalog: 'Mực ống',
    slug: 'muc-ong-hap-hanh-gung',
  },
  {
    price: 200000,
    unit: 'kg',
    name: 'Mực ống nướng mọi',
    image: 'https://img-global.cpcdn.com/recipes/e8d781840203da24/1200x630cq70/photo.jpg',
    catalog: 'Mực ống',
    slug: 'muc-ong-nuong-moi',
  },
  {
    price: 300000,
    unit: 'kg',
    name: 'Mực sữa chiên nước mắm',
    image: 'https://thegioiamthuc.com/wp-content/uploads/2018/07/muc-sua-chien.jpg',
    catalog: 'Mực sữa',
    slug: 'muc-sua-chien-nuoc-mam',
  },
  {
    price: 300000,
    unit: 'kg',
    name: 'Mực sữa hấp hành gừng',
    image: 'https://haisanmoingay.com/wp-content/uploads/2015/03/muc-trung-hap-2-e1464922397755.jpg',
    catalog: 'Mực sữa',
    slug: 'muc-sua-hap-hanh-gung',
  },
  {
    price: 300000,
    unit: 'kg',
    name: 'Mực sữa nướng muối ớt',
    image:
      'http://file.hstatic.net/1000030244/file/cach-nau-muc-sua-chien-nuoc-mam-thom-ngon-dua-het-noi-com_grande.jpg',
    catalog: 'Mực sữa',
    slug: 'muc-sua-nuong-muoi-ot',
  },
  {
    price: 300000,
    unit: 'kg',
    name: 'Mực sữa sốt me cay',
    image: 'https://afamilycdn.com/Images/Uploaded/Share/2011/01/14/c50mucsuachien.jpg',
    catalog: 'Mực sữa',
    slug: 'muc-sua-sot-me-cay',
  },
  {
    price: 320000,
    unit: 'dĩa',
    name: 'Mực 1 nắng nướng mọi',
    image: 'https://cdn.tgdd.vn/2021/04/CookRecipe/Avatar/muc-mot-nang-nuong-muoi-ot-thumbnail.jpg',
    catalog: 'Mực 1 nắng',
    slug: 'muc-1-nang-nuong-moi',
  },
  {
    price: 320000,
    unit: 'dĩa',
    name: 'Mực 1 nắng nướng sa tế',
    image: 'https://atuankhang.vn/wp-content/uploads/2020/06/muc-1-nang-nuong-sa-te.jpg',
    catalog: 'Mực 1 nắng',
    slug: 'muc-1-nang-nuong-sa-te',
  },
  {
    price: 320000,
    unit: 'dĩa',
    name: 'Mực 1 nắng nướng muối ớt',
    image:
      'https://pastaxi-manager.onepas.vn/content/uploads/articles/vuonghoai/muc-1-nang/cach-lam-muc-mot-nang-nuong-4.jpg',
    catalog: 'Mực 1 nắng',
    slug: 'muc-1-nang-nuong-muoi-ot',
  },
  {
    price: 320000,
    unit: 'dĩa',
    name: 'Mực 1 nắng chiên nước mắm',
    image: 'https://muckho.vn/wp-content/uploads/2014/09/muc-mot-nang-chien-nuoc-mam.jpg',
    catalog: 'Mực 1 nắng',
    slug: 'muc-1-nang-chien-nuoc-mam',
  },
  {
    price: 320000,
    unit: 'dĩa',
    name: 'Mực 1 nắng hấp hành gừng',
    image: 'https://tuhaisan.vn/wp-content/uploads/2019/08/muc-hap-hanh.jpg',
    catalog: 'Mực 1 nắng',
    slug: 'muc-1-nang-hap-hanh-gung',
  },
  {
    price: 85000,
    unit: 'thố',
    name: 'Nghêu hấp xả',
    image:
      'https://www.unileverfoodsolutions.com.vn/dam/global-ufs/mcos/phvn/vietnam/calcmenu/recipes/VN-recipes/fish-&-other-seafood-dishes/thai-steamed-clams/main-header.jpg',
    catalog: 'Các món nghêu',
    slug: 'ngheu-hap-xa',
  },
  {
    price: 85000,
    unit: 'thố',
    name: 'Nghêu hấp thái',
    image: 'https://cdn.tgdd.vn/2021/11/CookDish/cach-lam-ngheu-hap-thai-don-gian-ngon-kho-cuong-avt-1200x676.jpg',
    catalog: 'Các món nghêu',
    slug: 'ngheu-hap-thai',
  },
  {
    price: 85000,
    unit: 'thố',
    name: 'Nghêu hấp gừng',
    image: 'https://bizweb.dktcdn.net/100/400/734/products/foody-oc-hat-de-560-637053590567238987.jpg',
    catalog: 'Các món nghêu',
    slug: 'ngheu-hap-gung',
  },
  {
    price: 85000,
    unit: 'dĩa',
    name: 'Nghêu xào lá quế',
    image:
      'https://2.bp.blogspot.com/-IjtS1A1e2BQ/VSdK-4fi47I/AAAAAAAAApQ/iypGhtEM70o/w1200-h630-p-k-no-nu/ngao-xao-hung-que.jpg',
    catalog: 'Các món nghêu',
    slug: 'ngheu-xao-la-que',
  },
  {
    price: 85000,
    unit: 'dĩa',
    name: 'Nghêu sốt thái',
    image:
      'http://cdn.tgdd.vn/Files/2021/08/24/1377439/cach-lam-ngao-xao-sot-chua-ngot-kieu-thai-cay-ngon-kho-cuong-202108241240111439.jpg',
    catalog: 'Các món nghêu',
    slug: 'ngheu-sot-thai',
  },
  {
    price: 125000,
    unit: 'dĩa',
    name: 'Sò huyết nướng mọi',
    image: 'https://taucaotoc.vn/wp-content/uploads/2020/12/So-huyet-nuong-moi.jpg',
    catalog: 'Sò huyết',
    slug: 'so-huyet-nuong-moi',
  },
  {
    price: 125000,
    unit: 'dĩa',
    name: 'Sò huyết rang me',
    image: 'https://daubepgiadinh.vn/wp-content/uploads/2018/04/so-huyet-rang-me-600x400.jpg',
    catalog: 'Sò huyết',
    slug: 'so-huyet-rang-me',
  },
  {
    price: 125000,
    unit: 'dĩa',
    name: 'Sò huyết cháy tỏi',
    image: 'https://nghebep.com/wp-content/uploads/2018/07/so-huyet-xao-toi.jpg',
    catalog: 'Sò huyết',
    slug: 'so-huyet-chay-toi',
  },
  {
    price: 125000,
    unit: 'dĩa',
    name: 'Sò huyết Lacoste',
    image: 'https://anh.24h.com.vn/upload/3-2012/images/2012-08-25/1345862828-so-huyet-trung-luoc-soi.jpg',
    catalog: 'Sò huyết',
    slug: 'so-huyet-lacoste',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Sò lông nướng mỡ hành',
    image: 'https://www.noichienkhongdau.com/wp-content/uploads/2022/04/so-huyet-nuong-bang-noi-chien-khong-dau-1.jpg',
    catalog: 'Sò lông',
    slug: 'so-long-nuong-mo-hanh',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Sò lông hấp xả',
    image: 'https://haisancoto.com/uploads/images/so-long-hap-sa-thom-ngon.jpg',
    catalog: 'Sò lông',
    slug: 'so-long-hap-xa',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Sò điệp nướng phô mai',
    image:
      'https://phanphoiruounhapkhau.com/wp-content/uploads/2021/05/thumb-goi-y-3-mon-an-lam-tu-so-diep-ngon-nuc-long.jpg',
    catalog: 'Sò điệp',
    slug: 'so-diep-nuong-pho-mai',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Sò điệp nướng bơ tỏi',
    image: 'http://file.hstatic.net/1000357278/article/so_diep2_cd0c40ccdfc84c8497df1d546a958b25.jpg',
    catalog: 'Sò điệp',
    slug: 'so-diep-nuong-bo-toi',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Sò điệp hấp tỏi',
    image: 'https://songkhoe.medplus.vn/wp-content/uploads/2020/04/so-diep-hap-toi.png',
    catalog: 'Sò điệp',
    slug: 'so-diep-hap-toi',
  },
  {
    price: 20000,
    unit: 'con',
    name: 'Sò mai nướng mỡ hành',
    image:
      'https://bizweb.dktcdn.net/100/022/012/articles/56994062-342961996337377-4377230956398903296-n.jpg?v=1554792828900',
    catalog: 'Sò mai',
    slug: 'so-mai-nuong-mo-hanh',
  },
  {
    price: 20000,
    unit: 'con',
    name: 'Sò mai nướng phô mai',
    image: 'https://ocvuvinhkhanh.com/wp-content/uploads/2019/01/so-mai-nuong-pho-mai-2.jpg',
    catalog: 'Sò mai',
    slug: 'so-mai-nuong-pho-mai',
  },
  {
    price: 235000,
    unit: 'kg',
    name: 'Ốc hương xào bơ tỏi',
    image: 'http://hoamaiquan.com/wp-content/uploads/2022/03/oc-huong-sot-trung-muoi-1.jpg',
    catalog: 'Ốc hương',
    slug: 'oc-huong-xao-bo-toi',
  },
  {
    price: 235000,
    unit: 'kg',
    name: 'Ốc hương xào me',
    image: 'https://nghebep.com/wp-content/uploads/2019/01/oc-huong-xao-me.jpg',
    catalog: 'Ốc hương',
    slug: 'oc-huong-xao-me',
  },
  {
    price: 235000,
    unit: 'kg',
    name: 'Ốc hương xào xả ớt',
    image:
      'https://file.hstatic.net/1000030244/file/oc-huong-lam-gi-ngon-2_4344c53c76a7490bbf9e0a97d507c72b_grande.jpg',
    catalog: 'Ốc hương',
    slug: 'oc-huong-xao-xa-ot',
  },
  {
    price: 235000,
    unit: 'kg',
    name: 'Ốc hương hấp xả',
    image: 'https://yummyday.vn/uploads/images/cach-lam-oc-huong-hap-sa.jpg',
    catalog: 'Ốc hương',
    slug: 'oc-huong-hap-xa',
  },
  {
    price: 235000,
    unit: 'kg',
    name: 'Ốc hương nướng mọi',
    image: 'https://yummyday.vn/uploads/images/cach-nuong-oc-huong.jpg',
    catalog: 'Ốc hương',
    slug: 'oc-huong-nuong-moi',
  },
  {
    price: 235000,
    unit: 'kg',
    name: 'Ốc hương nướng muối ớt',
    image:
      'https://pastaxi-manager.onepas.vn/content/uploads/articles/cach-lam-oc-h%C6%B0%C6%A1ng-nuong/cach-lam-oc-huong-nuong-8.jpg',
    catalog: 'Ốc hương',
    slug: 'oc-huong-nuong-muoi-ot',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Ốc móng tay xào bơ tỏi',
    image: 'https://chefdzung.com.vn/uploads/images/ngoc-linh/1568947115oc-mong-tay-xao-toi.jpg',
    catalog: 'Ốc móng tay',
    slug: 'oc-mong-tay-xao-bo-toi',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Ốc móng tay xào me',
    image: 'http://monngondongian.com/wp-content/uploads/2022/11/oc-mong-tay-xao-me.jpg',
    catalog: 'Ốc móng tay',
    slug: 'oc-mong-tay-xao-me',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Ốc móng tay xào xả ớt',
    image: 'https://i.ytimg.com/vi/jq2tGKa5Q9U/maxresdefault.jpg',
    catalog: 'Ốc móng tay',
    slug: 'oc-mong-tay-xao-xa-ot',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Ốc móng tay sốt trứng muối',
    image:
      'http://cdn.tgdd.vn/Files/2022/01/11/1410203/bi-quyet-lam-oc-mong-tay-sot-trung-muoi-beo-ngay-chuan-vi-nha-hang-202201110902054532.jpg',
    catalog: 'Ốc móng tay',
    slug: 'oc-mong-tay-sot-trung-muoi',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Ốc móng tay xào rau muống',
    image: 'https://img-global.cpcdn.com/recipes/7e4a23b15e89c43e/1200x630cq70/photo.jpg',
    catalog: 'Ốc móng tay',
    slug: 'oc-mong-tay-xao-rau-muong',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Ốc móng tay xào lá quế',
    image: 'https://cdn.tgdd.vn/2021/03/CookProduct/Ocmongtayxaolaque-1200x676.jpg',
    catalog: 'Ốc móng tay',
    slug: 'oc-mong-tay-xao-la-que',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Ốc mỡ cháy tỏi',
    image: 'https://cdn.daynauan.info.vn/wp-content/uploads/2018/07/oc-mo-xao-toi.jpg',
    catalog: 'Ốc mỡ',
    slug: 'oc-mo-chay-toi',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Ốc mỡ xào me',
    image: 'https://canghaisan.com/wp-content/uploads/2020/11/132-2.jpg',
    catalog: 'Ốc mỡ',
    slug: 'oc-mo-xao-me',
  },
  {
    price: 135000,
    unit: 'dĩa',
    name: 'Ốc mỡ xo rau muống',
    image: 'https://haisan.online/wp-content/uploads/2022/01/oc-mo-xao-3.jpg',
    catalog: 'Ốc mỡ',
    slug: 'oc-mo-xo-rau-muong',
  },
  {
    price: 445000,
    unit: 'kg',
    name: 'Cua rang me',
    image: 'https://daubepgiadinh.vn/wp-content/uploads/2018/04/cua-rang-me.jpg',
    catalog: 'Các món cua',
    slug: 'cua-rang-me',
  },
  {
    price: 445000,
    unit: 'kg',
    name: 'Cua hấp xả',
    image: 'https://nhahanghaisanlangchai.com/upload/images/cua_hap_gung_xa.png',
    catalog: 'Các món cua',
    slug: 'cua-hap-xa',
  },
  {
    price: 445000,
    unit: 'kg',
    name: 'Cua nướng mọi',
    image: 'https://bepvietnam.vn/public/files/editor-upload/files/cua-nuong.jpg',
    catalog: 'Các món cua',
    slug: 'cua-nuong-moi',
  },
  {
    price: 145000,
    unit: 'dĩa',
    name: 'Càng ghẹ rang me',
    image: 'https://bepmina.vn/wp-content/uploads/2021/05/cach-lam-cang-ghe-rang-me.jpeg',
    catalog: 'Các món ghẹ',
    slug: 'cang-ghe-rang-me',
  },
  {
    price: 145000,
    unit: 'dĩa',
    name: 'Càng ghẹ rang muối ớt',
    image: 'https://banhtrangnhubinh.com/wp-content/uploads/2019/06/cang-ghe-rang-muoi-ot-2.jpg',
    catalog: 'Các món ghẹ',
    slug: 'cang-ghe-rang-muoi-ot',
  },
  {
    price: 445000,
    unit: 'kg',
    name: 'Ghẹ Hấp',
    image:
      'https://image-us.eva.vn/upload/4-2021/images/2021-11-12/1636682021-440-thumbnail-width640height480_schema_article.jpg',
    catalog: 'Các món ghẹ',
    slug: 'ghe-hap',
  },
  {
    price: 445000,
    unit: 'kg',
    name: 'Ghẹ sốt me',
    image:
      'https://danviet.mediacdn.vn/upload/4-2017/images/2017-11-09/Ghe-sot-me-chua-chua-ngot-ngot-ngon-chay-nuoc-mieng-_mg_7854-1510222520-width660height440.jpg',
    catalog: 'Các món ghẹ',
    slug: 'ghe-sot-me',
  },
  {
    price: 35000,
    unit: 'con',
    name: 'Hàu nướng phô mai',
    image: 'https://cdn.netspace.edu.vn/images/2020/07/27/cach-lam-hau-nuong-pho-mai-4-1024.jpg',
    catalog: 'Các món hàu',
    slug: 'hau-nuong-pho-mai',
  },
  {
    price: 35000,
    unit: 'con',
    name: 'Hàu nướng mỡ hành',
    image: 'https://gatrongcooking.com/media/2021/12/hau-nuong-mo-hanh/hau-nuong-mo-hanh-16x9.jpg',
    catalog: 'Các món hàu',
    slug: 'hau-nuong-mo-hanh',
  },
  {
    price: 35000,
    unit: 'con',
    name: 'Hàu nướng bơ tỏi',
    image: 'https://cdn.tgdd.vn/2021/04/CookRecipe/GalleryStep/thanh-pham-1797.jpg',
    catalog: 'Các món hàu',
    slug: 'hau-nuong-bo-toi',
  },
  {
    price: 35000,
    unit: 'con',
    name: 'Hàu Mù tạt',
    image: 'https://cdn.bepcuoi.com/media/720-hau-sua-cham-mu-tat-bepcuoi-210.jpg',
    catalog: 'Các món hàu',
    slug: 'hau-mu-tat',
  },
  {
    price: 180000,
    unit: 'con',
    name: 'Cá sapa nướng giấy bạc',
    image:
      'http://cdn.tgdd.vn/Files/2021/02/06/1326120/cach-lam-ca-saba-nuong-giay-bac-ngon-ngot-khong-bi-tanh-202102061248530666.jpg',
    catalog: 'Cá sapa',
    slug: 'ca-sapa-nuong-giay-bac',
  },
  {
    price: 180000,
    unit: 'con',
    name: 'Cá sapa nướng mỡ hành',
    image:
      'http://cdn.tgdd.vn/Files/2021/10/01/1387158/hoc-ngay-cach-lam-mon-ca-saba-nuong-mo-hanh-don-gian-de-lam-tai-nha-202112311420231583.jpg',
    catalog: 'Cá sapa',
    slug: 'ca-sapa-nuong-mo-hanh',
  },
  {
    price: 180000,
    unit: 'con',
    name: 'Cá sapa nướng tiêu xanh',
    image: 'https://i.ytimg.com/vi/ympCytvevks/maxresdefault.jpg',
    catalog: 'Cá sapa',
    slug: 'ca-sapa-nuong-tieu-xanh',
  },
  {
    price: 180000,
    unit: 'con',
    name: 'Cá sapa nướng muối ớt',
    image: 'https://nld.mediacdn.vn/thumb_w/540/2017/img-5176-1488518036499.jpg',
    catalog: 'Cá sapa',
    slug: 'ca-sapa-nuong-muoi-ot',
  },
  {
    price: 50000,
    unit: 'dĩa',
    name: 'Rau câu',
    image:
      'https://thebazan.vn/wp-content/uploads/2020/05/c%C3%A1ch-l%C3%A0m-rau-c%C3%A2u-c%C3%A0-ph%C3%AA-s%E1%BB%AFa.jpg',
    catalog: 'Món tráng miệng',
    slug: 'rau-cau',
  },
  {
    price: 50000,
    unit: 'dĩa',
    name: 'Dĩa trái cây',
    image:
      'https://skibanen.com/wp-content/uploads/2021/08/cach-trang-tri-dia-trai-cay-trang-mieng-don-gian-de-thuc-hien.jpg',
    catalog: 'Món tráng miệng',
    slug: 'dia-trai-cay',
  },
  {
    price: 200000,
    unit: 'lon',
    name: 'Pepsi',
    image: 'https://product.hstatic.net/1000141988/product/nuoc_ngot_pepsi_36daafe416c7499aacd53694c72ef692.jpg',
    catalog: 'Nước ngọt',
    slug: 'pepsi',
  },
  {
    price: 20000,
    unit: 'lon',
    name: 'Coca Cola',
    image: 'https://i.ytimg.com/vi/nrwtnncuu7Q/maxresdefault.jpg',
    catalog: 'Nước ngọt',
    slug: 'coca-cola',
  },
  {
    price: 18000,
    unit: 'lon',
    name: 'Bí đao',
    image:
      'https://cdn.tgdd.vn/Products/Images/8938/111575/bhx/6-lon-tra-bi-dao-wonderfarm-310ml-202103290403574758.jpg',
    catalog: 'Nước ngọt',
    slug: 'bi-dao',
  },
  {
    price: 18000,
    unit: 'lon',
    name: '7 up',
    image:
      'https://product.hstatic.net/1000141988/product/nuoc_ngot_7up_huong_chanh_6f65e871be734190a0b49615919100b3.jpg',
    catalog: 'Nước ngọt',
    slug: '7-up',
  },
  {
    price: 22000,
    unit: 'lon',
    name: 'Mirinda Soda Kem',
    image:
      'https://product.hstatic.net/1000141988/product/__loc_6_lon___nuoc_ngot_mirinda_soda_kem_320_ml_0774f0fae5d14c26828143ad7cb95bc7.jpg',
    catalog: 'Nước ngọt',
    slug: 'mirinda-soda-kem',
  },
  {
    price: 200000,
    unit: 'lon',
    name: 'Heniken xanh',
    image: 'https://angonstore.vn/img/p/bia-heineken-ha-lan-5-lon-330ml-x-20-lon-p702.jpg',
    catalog: 'Bia',
    slug: 'heniken-xanh',
  },
  {
    price: 25000,
    unit: 'lon',
    name: 'Heniken bạc',
    image: 'https://cdn.tgdd.vn/Products/Images/2282/200638/bhx/6-lon-bia-heineken-silver-330ml-202301152339137476.jpg',
    catalog: 'Bia',
    slug: 'heniken-bac',
  },
  {
    price: 20000,
    unit: 'lon',
    name: 'Tiger',
    image: 'https://cdn.tgdd.vn/Products/Images/2282/171021/bhx/6-lon-bia-tiger-330ml-202103162330599969.jpg',
    catalog: 'Bia',
    slug: 'tiger',
  },
  {
    price: 25000,
    unit: 'lon',
    name: 'Tiger Crystal',
    image:
      'https://sieuthihoaba.com.vn/wp-content/uploads/2020/08/6-lon-bia-tiger-crystal-330ml-202003281744582262.jpg',
    catalog: 'Bia',
    slug: 'tiger-crystal',
  },
  {
    price: 22000,
    unit: 'lon',
    name: 'Sài Gòn Special',
    image: 'https://saigonspecial.com/wp-content/uploads/2020/06/thiet-ke-bia-sai-gon-special-chai-lun.png',
    catalog: 'Bia',
    slug: 'sai-gon-special',
  },
  {
    price: 180000,
    unit: 'chai',
    name: 'Vodka Men',
    image: 'https://douongngoainhap.com/wp-content/uploads/image/05_2019/ruou%20vodka%20men.jpg',
    catalog: 'Rượu',
    slug: 'vodka-men',
  },
  {
    price: 150000,
    unit: 'chai',
    name: 'Vodka Hà Nội',
    image: 'https://1001hotel.com.vn/Uploads/_thumbs/_Uploads_images_SieuThi_ruou_question-vodka.jpg-700x700.jpg',
    catalog: 'Rượu',
    slug: 'vodka-ha-noi',
  },
  {
    price: 18000,
    unit: 'xị',
    name: 'Rượu trắng',
    image: 'https://doisun.com.vn/wp-content/uploads/2022/04/r%C6%B0%E1%BB%A3u-n%E1%BA%BFp-tr%E1%BA%AFng-7.jpg',
    catalog: 'Rượu',
    slug: 'ruou-trang',
  },
  {
    price: 150000,
    unit: 'chai',
    name: 'Rượu chuối hột',
    image: 'https://ruouviet.com.vn/wp-content/uploads/2022/02/NEW__GS_9127-copy-scaled.jpg',
    catalog: 'Rượu',
    slug: 'ruou-chuoi-hot',
  },
];

[
  {
    name: 'Các món Khai Vị',
    slug: 'cac-mon-khai-vi',
    image: 'https://bucket.nhanh.vn/033a84-66619/album/albumCT/20200309_7ecutTT43nDaW56PNTdh8AQd.jpg',
  },
  {
    name: 'Các món gỏi',
    slug: 'cac-mon-goi',
    image:
      'https://cdn.tgdd.vn/Files/2022/04/04/1423782/goi-y-8-mon-nguoi-khai-vi-cho-nhung-buoi-tiec-hoi-hop-voi-gia-dinh-202204040912057499.jpg',
  },
  {
    name: 'Các món súp',
    slug: 'cac-mon-sup',
    image: 'https://cdn.daynauan.info.vn/wp-content/uploads/2020/08/sup-tom.jpg',
  },
  {
    name: 'Các món cháo',
    slug: 'cac-mon-chao',
    image: 'https://www.hoidaubepaau.com/wp-content/uploads/2019/06/cach-nau-chao-hai-san.jpg',
  },
  {
    name: 'Cơm chiên',
    slug: 'com-chien',
    image: 'https://nauantainha.com/wp-content/uploads/cooked/images/recipes/recipe_1501.jpg',
  },
  {
    name: 'Mì-miến xào',
    slug: 'mi-mien-xao',
    image: 'https://cdn.beptruong.edu.vn/wp-content/uploads/2013/08/mon-mi-xao-hai-san.jpg',
  },
  {
    name: 'Các món lẩu',
    slug: 'cac-mon-lau',
    image:
      'https://www.unileverfoodsolutions.com.vn/dam/global-ufs/mcos/phvn/vietnam/calcmenu/recipes/VN-recipes/fish-&-other-seafood-dishes/seafood-hotpot/main-header.jpg',
  },
  {
    name: 'Tôm sú',
    slug: 'tom-su',
    image: 'https://cdn.jamja.vn/blog/wp-content/uploads/2018/01/mon-ngon-tu-tom-su.jpg',
  },
  {
    name: 'Tôm hùm',
    slug: 'tom-hum',
    image:
      'http://cdn.tgdd.vn/Files/2020/02/28/1239091/cac-cach-hap-tom-hum-cuc-ky-ngon-ma-don-gian-tai-nha-202112310954112612.jpg',
  },
  {
    name: 'Mực lá',
    slug: 'muc-la',
    image:
      'https://cdn.tgdd.vn/Products/Images/8782/234548/bhx/muc-la-dai-duong-lam-sach-tui-500g-202101231424451462.jpg',
  },
  {
    name: 'Mực ống',
    slug: 'muc-ong',
    image: 'https://cdn.tgdd.vn/Products/Images/8782/245067/bhx/muc-ong-tui-300g-202110011419217330.jpg',
  },
  {
    name: 'Mực sữa',
    slug: 'muc-sua',
    image: 'https://vuacamuc.com/wp-content/uploads/2018/07/muc-sua-nuong-muoi-ot.jpg',
  },
  {
    name: 'Mực 1 nắng',
    slug: 'muc-1-nang',
    image: 'https://haisananhlan.com/wp-content/uploads/2020/08/muc-1-nang-1.jpg',
  },
  {
    name: 'Các món nghêu',
    slug: 'cac-mon-ngheu',
    image: 'https://file.hstatic.net/1000030244/file/ngheu-trang-song_fdd02e9a9ee24de286891db382bc5f85_grande.jpg',
  },
  {
    name: 'Sò huyết',
    slug: 'so-huyet',
    image: 'https://vinmec-prod.s3.amazonaws.com/images/20210405_191958_048329_an-so-huyet.max-1800x1800.jpg',
  },
  {
    name: 'Sò lông',
    slug: 'so-long',
    image: 'https://crabseafood.vn/wp-content/uploads/2021/04/48-17-510x510.png',
  },
  {
    name: 'Sò điệp',
    slug: 'so-diep',
    image: 'https://www.noichienkhongdau.com/wp-content/uploads/2022/03/so-diep-nuong-bang-noi-chien-khong-dau-3.jpg',
  },
  {
    name: 'Sò mai',
    slug: 'so-mai',
    image: 'https://kenh14cdn.com/2018/2/11/a4-1518337830498294304068.jpg',
  },
  {
    name: 'Ốc hương',
    slug: 'oc-huong',
    image: 'https://product.hstatic.net/200000419887/product/oc_huong_6c6258fca4ca407bbd47db749105d9ee_master.png',
  },
  {
    name: 'Ốc móng tay',
    slug: 'oc-mong-tay',
    image: 'http://monngondongian.com/wp-content/uploads/2022/11/oc-mong-tay-xao-me.jpg',
  },
  {
    name: 'Ốc mỡ',
    slug: 'oc-mo',
    image: 'https://cdn.daynauan.info.vn/wp-content/uploads/2018/07/oc-mo-xao-toi.jpg',
  },
  {
    name: 'Các món cua',
    slug: 'cac-mon-cua',
    image: 'https://cdn.tgdd.vn/2020/08/CookProduct/Untitled-1-1200x676-27.jpg',
  },
  {
    name: 'Các món ghẹ',
    slug: 'cac-mon-ghe',
    image: 'https://bepxua.vn/wp-content/uploads/2021/03/ghe.jpg',
  },
  {
    name: 'Các món hàu',
    slug: 'cac-mon-hau',
    image: 'https://vinmec-prod.s3.amazonaws.com/images/20210305_040333_519982_hau-la-thuc-pham-gi.max-1800x1800.jpg',
  },
  {
    name: 'Cá sapa',
    slug: 'ca-sapa',
    image: 'https://newfreshfoods.com.vn/datafiles/3/2020-12-16/thumb_16389531198792_23.jpg',
  },
  {
    name: 'Món tráng miệng',
    slug: 'mon-trang-mieng',
    image:
      'https://thebazan.vn/wp-content/uploads/2020/05/c%C3%A1ch-l%C3%A0m-rau-c%C3%A2u-c%C3%A0-ph%C3%AA-s%E1%BB%AFa.jpg',
  },
];
